INC_DIR=inc
SRC_DIR=src
OBJ_DIR=obj
EXE=app.exe
SRC=$(SRC_DIR)/main.cpp \
	$(SRC_DIR)/Calc.cpp

all: create-dirs $(EXE)

$(EXE): $(SRC)
	cl /EHsc /Fe$(EXE) /I$(INC_DIR) $(SRC)
	copy *.obj $(OBJ_DIR)
	del *.obj

clean:
	@if exist $(OBJ_DIR) rmdir /S /Q $(OBJ_DIR)
	@if exist $(EXE) del $(EXE)

create-dirs:
	@if not exist $(OBJ_DIR) mkdir $(OBJ_DIR)
