#include "serializer.h"

SERIALIZE_BASIC_IMPL(uint8_t)
SERIALIZE_BASIC_IMPL(uint16_t)
SERIALIZE_BASIC_IMPL(uint32_t)
SERIALIZE_BASIC_IMPL(uint64_t)
SERIALIZE_BASIC_IMPL(int8_t)
SERIALIZE_BASIC_IMPL(int16_t)
SERIALIZE_BASIC_IMPL(int32_t)
SERIALIZE_BASIC_IMPL(int64_t)
SERIALIZE_BASIC_IMPL(bool)
SERIALIZE_BASIC_IMPL(float)
SERIALIZE_BASIC_IMPL(double)
SERIALIZE_REF_IMPL(std::string)

